openapi: 3.0.0
info:
  title: AIT Real Estate Portal
  description: |
    This is a Real Estate Portal server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
- url: http://localhost:8080/api/v1
  description: Demo server
tags:
- name: property
  description: create, update, delete and view property
paths:
  /properties:
    get:
      tags: 
      - property
      summary: List properties filtered optionally by city
      parameters: 
      - name: city
        in: query
        description: city filter
        required: false
        schema:
          type: string
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ArrayOfProperties'
    post:
      tags:
      - property
      summary: Add new property for sale or for rent
      requestBody:
        $ref: '#/components/requestBodies/PropertyRequest'
      responses:
        200:
          description: Property added
          content:
            applicaiton/json:
              schema:
                $ref: '#/components/schemas/Property'
        405:
          description: Invalid input
  /properties/{id}:
    get:
      tags:
      - property
      summary: Find property by ID
      description: Returns a single property
      parameters:
      - name: id
        in: path
        description: ID of property to return
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Property'
        404:
          description: Property not found
    delete:
      tags:
      - property
      summary: Deletes a property
      parameters:
      - name: id
        in: path
        description: Property id to delete
        required: true
        schema:
          type: integer
          format: int64
      responses:
        200:
          description: Property deleted
        404:
          description: Property not found
components:
  schemas:
    Property:
      type: object
      properties:
        id:
          type: integer
          format: int64
        saleOrRent:
          type: string
          description: Is it for sale or for rent?
          enum:
          - SALE
          - RENT
        price:
          type: number
          format: double
        descripton:
          type: string
        city:
          type: string
        street:
          type: string
        picture:
          type: object
      example:
        id: 123456
        saleOrRent: SALE
        price: 100
        descripton: Apartament with a view to the Danube is for sale.
        city: Budapest
        street: Kossuth
        picture: [46,76,345]
    ArrayOfProperties:
      type: array
      items:  {
        $ref: '#/components/schemas/Property'
      }
    NewPropertyRequest:
      type: object
      properties:
        saleOrRent:
          type: string
          description: Is it for sale or rent?
          enum:
          - SALE
          - RENT
        price:
          type: number
          format: double
        descripton:
          type: string
        city:
          type: string
        picture:
          type: string
          format: binary
      example:
        saleOrRent: SALE
        price: 100
        descripton: Apartament with a view to the Danube is for sale.
        city: Budapest
        street: Kossuth
        picture: [4,4565,34]
  requestBodies:
    PropertyRequest:
      description: Property object that needs to be added to the portal
      content:
        multipart/form-data:
          schema:
            $ref: '#/components/schemas/NewPropertyRequest'
      required: true